// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/home": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/home";
  };
  "routes/_app.tsx": {
    id: "routes/_app";
    page: "/" | "/home";
  };
  "routes/_app._index.tsx": {
    id: "routes/_app._index";
    page: "/";
  };
  "routes/_app.home.tsx": {
    id: "routes/_app.home";
    page: "/home";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_app": typeof import("./app/routes/_app.tsx");
  "routes/_app._index": typeof import("./app/routes/_app._index.tsx");
  "routes/_app.home": typeof import("./app/routes/_app.home.tsx");
};